#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
APPNAME="$(awk -F= '$1 == "appname" { print $2 }' "$ROOT_DIR/manifest")"
VERSION="$(awk -F= '$1 == "version" { print $2 }' "$ROOT_DIR/manifest")"
TARGET_PLATFORM="${TARGET_PLATFORM:-x86}"
case "$TARGET_PLATFORM" in
  x86|arm)
    ;;
  *)
    echo "Unsupported TARGET_PLATFORM: $TARGET_PLATFORM. Use x86 or arm." >&2
    exit 1
    ;;
esac
OUT_DIR="$ROOT_DIR/dist"
STAGING_DIR="$OUT_DIR/build/$APPNAME"
OUT_FILE="$OUT_DIR/${APPNAME}-${VERSION}-${TARGET_PLATFORM}.fpk"
FNPACK_BIN="${FNPACK_BIN:-}"

mkdir -p "$OUT_DIR"

if [ -z "$FNPACK_BIN" ]; then
  if command -v fnpack >/dev/null 2>&1; then
    FNPACK_BIN="$(command -v fnpack)"
  elif [ -x "$ROOT_DIR/tools/fnpack" ]; then
    FNPACK_BIN="$ROOT_DIR/tools/fnpack"
  else
    echo "fnpack not found. Install it or set FNPACK_BIN=/absolute/path/to/fnpack." >&2
    echo "Download: https://static2.fnnas.com/fnpack/fnpack-1.2.3-darwin-arm64" >&2
    exit 1
  fi
fi

node - "$ROOT_DIR" "$STAGING_DIR" "$OUT_FILE" "$TARGET_PLATFORM" "${DEPENDENCY_BASE_URLS:-}" <<'NODE'
const fs = require("fs");
const path = require("path");

const [, , rootDir, stagingDir, outFile, targetPlatform, dependencyBaseUrls] = process.argv;
fs.rmSync(stagingDir, { recursive: true, force: true });
fs.mkdirSync(stagingDir, { recursive: true });
fs.rmSync(outFile, { force: true });

for (const entry of ["app", "cmd", "config", "wizard"]) {
  fs.cpSync(path.join(rootDir, entry), path.join(stagingDir, entry), {
    recursive: true,
    filter: (src) => {
      const base = path.basename(src);
      if (base === ".DS_Store") return false;
      if (base === "node_modules") return false;
      if (/^node_modules-linux-.*\.tgz(\.sha256)?$/.test(base)) return false;
      if (base === "node_modules-linux.tgz") return false;
      return true;
    },
  });
}

for (const file of ["manifest", "ICON.PNG", "ICON_256.PNG"]) {
  fs.copyFileSync(path.join(rootDir, file), path.join(stagingDir, file));
}

const manifestPath = path.join(stagingDir, "manifest");
const manifest = fs.readFileSync(manifestPath, "utf8")
  .replace(/^platform\s*=.*$/m, `platform=${targetPlatform}`);
fs.writeFileSync(manifestPath, manifest);

if (dependencyBaseUrls.trim()) {
  const sourcesPath = path.join(stagingDir, "app", "dependency-sources.conf");
  const lines = dependencyBaseUrls
    .split(/[\n\s]+/)
    .map((line) => line.trim())
    .filter(Boolean);
  fs.writeFileSync(
    sourcesPath,
    [
      "# Generated by scripts/build-fpk.sh.",
      "# One base URL per line. The installer appends the architecture-specific archive name.",
      ...lines,
      "",
    ].join("\n"),
  );
}
NODE

(
  cd "$OUT_DIR"
  "$FNPACK_BIN" build --directory "$STAGING_DIR"
)

if [ -f "$OUT_DIR/${APPNAME}.fpk" ]; then
  mv "$OUT_DIR/${APPNAME}.fpk" "$OUT_FILE"
elif [ ! -f "$OUT_FILE" ]; then
  echo "fnpack finished but no expected fpk was found in $OUT_DIR." >&2
  exit 1
fi

echo "$OUT_FILE"
